default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: mypassword
  pool: 5
development:
  <<: *default
  database: estac_development
test:
  <<: *default
  database: estac_test
production:
  <<: *default
  database: estac_production
